apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ARTIFACT_NAME
  description: Spring Cloud Architecture on TAP ARTIFACT_NAME
  tags:
    - sc-architecture
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=ARTIFACT_NAME'
spec:
  type: service
  lifecycle: experimental
  owner: team-vmware-tanzu-se
  system: sc-architecture-system
  dependsOn:
  - Resource:configserver
  - Resource:observability