#@ load("@ytt:data", "data")
---
apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: TrainingPortal
metadata:
  name: tap-spring-developer-workshops
  annotations:
    kapp.k14s.io/update-strategy: always-replace
spec:
  portal:
    title: Workshops for Spring developers
    password: #@ data.values.training_portal_password
    registration:
      type: anonymous
    ingress:
        hostname: spring-developer-workshops
    updates:
      workshop: true
    sessions:
      maximum: 40
    reserved: 0
  workshops:
    - name: tap-spring-developer-workshops
      capacity: 40
      reserved: 1
      expires: 4h
      orphaned: 1h