apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: order-service
  annotations:
    autoscaling.knative.dev/min-scale: "1"
  labels:
    app.kubernetes.io/part-of: order-service
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  source:
    git:
      url: SOURCE_GIT_URL
      ref:
        branch: SOURCE_GIT_BRANCH
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"