apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: sc-architecture-system
  description: Spring Cloud Architecture on TAP
  annotations:
    'backstage.io/techdocs-ref': url:https://github.com/timosalm/tap-spring-developer-workshop/tree/main/setup/catalog
spec:
  owner: team-vmware-tanzu-se
