apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: ARTIFACT_NAME
  annotations:
    autoscaling.knative.dev/min-scale: "1"
    autoscaling.knative.dev/max-scale: "3"
    autoscaling.knative.dev/target: "50"
  labels:
    app.kubernetes.io/part-of: ARTIFACT_NAME
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  source:
    git:
      url: SOURCE_GIT_BASE_URL/ARTIFACT_NAME.git
      ref:
        branch: SOURCE_GIT_BRANCH
  build:
    env:
    - name: BP_JVM_VERSION
      value: "JAVA_VERSION"