spring:
  application.name: shipping-service # for config server
  config.import: "optional:configtree:${SERVICE_BINDING_ROOT}/config-server/"
  cloud.stream.bindings:
      shipOrder-in-0.destination: ${shipping.in-exchange}
      shipOrder-out-0.destination: ${shipping.out-exchange}

management:
  endpoint.restart.enabled: true
  endpoints.web.exposure.include: "*"
  tracing.sampling.probability: 1.0

shipping:
  in-exchange: order-shipping-exchange
  out-exchange: order-delivered-exchange
  duration: 1000